name: Build and Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master, feature/aa-29-continuous-deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up our JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Run Tests
      run: ./gradlew test

    - name: Build Project
      run: ./gradlew assemble

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
